### ISSUE TITLE
Hammer.js pinch swipe extension: Fix known issues

### ISSUE THREAD

**Issue by thomasfrobieter** [juek/Colorbox-Extender#3]
~~Thought i've fixed the webkit swipe issue, but still exist. I will fix it tomorrow.~~ [DONE]

Found following issues i will try to fix within the next days:
- ~~webkit based browsers swipe out, but not in again~~
- ~~Swipe animation look's ugly while the image is still loading~~
- Doubletap zoom only work's if no pinchzoom was performed before
- Reduce CSS, we do not need all the animate.css animations
- Swipe up / down to close Colorbox is not working
- Check if the colorbox content is an image & check if theres is more then one image (otherwise disable swipe)
- (cleanup the chaotic code ;)

**Comment by thomasfrobieter** [comment]
Fixed the webkit issue. Just switched from cbox_load callback to cbox_complete.

**Comment by juek** [comment]
As it seems that jQuery and CSS animations compete here and there, so maybe better get rid of animate.css classes where jQ already does the job. 

BTW: Since Colorbox preloads adjacent images, I wonder if we couldn't just smuggle them in for swiping, using one off the callbacks.

**Comment by thomasfrobieter** [comment]
Good morning @juek,

the animation look's really smooth on my android phone. The Colorbox container just change the height, animate.css does just the swipe animation. 
I prefer css animations as other developers can simply override them just using css. I just turned off Colorbox transition, so we can prevent collisions this way?!
If you agree, i will add css transition for the height animation later.

In my Typesetter instance preloading seemed to be disabled? I enabled it now inside the extensions init.js.

**Comment by juek** [comment]
Hmm, yes, maybe a drawback here of having both extensions and styles options. 
The question is, which one we should give CSS precedence... Currently styles overrule extensions and even !important will not help, since we have to fight so many Colorbox inline styles, we already need !important quite a lot. So precendence matters. (we need !reallyImportant, !evenMoreImportant and !crucial :)

**Comment by thomasfrobieter** [comment]
LOL .. yeah welcome to the !important-hell.

First thought on this: What if we add a setting for "transition", which affects any style and any extension. So we can add a custom transition option "none (Use CSS Animations)" (additonal to the simple "none" and of course the native Colorbox transition presets). If this custom option is set, we will add a class (and of course the transition css code to our css file) to the colorbox container .colorbox--css-transition and disable the native transition by $.colorbox.settings.transition="none"; ...

But that could also be total nonsense. I'll think about it ... maybe everything about transition / animation should be up to the current style.. i don't know.

**Comment by juek** [comment]
But adding all possible Colorbox options as settings to the Admin page is nor a bad idea at all.

**Comment by juek** [comment]
> adding all possible Colorbox options as settings ... idea.

Bad idea, baaaad idea (almost 60 options :-)

**Comment by florincatalin** [comment]
> But adding all possible Colorbox options as settings to the Admin page is nor a bad idea at all.

testing using PC mouse works just saw that double-clicking the image appears as though it would be framed in an iframe
I saw on the the hammer.js page that we could also use Shift + mouse, to emulate gestures, but it did not work for me
maybe this option, with hammer.js, is most appropriate for android phones
I think for PCs would be more appropriate first option, zoom, which works great, thanks Juek
_should be left as many options, and the user can choose, but also keep code clean and simple_
