### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by a2exfr** [juek/Colorbox-Extender#5]
Hi.
The first try and some bugs here. 

@thomasfrobieter 
When using swipe extend. 
Fast open and closing colorbox cause to it's preloading animation to stay on page. 
To reproduce just quickly open and close some gallery images, sometimes this two divs is stay on the top.
```
<div id="cboxLoadingOverlay" style="float: left; display: none;"></div>
<div id="cboxLoadingGraphic" style="float: left; display: block;"></div>

```
Solution is to comment this [two lines](https://github.com/juek/Colorbox-Extender/blob/master/extensions/pinch_swipe/init.js#L135-L136) in init.js 
```
$.colorbox.settings.preloading=true;
$.colorbox.settings.transition="none";
```

Also when using jquerry zoom and simple box1 style - image appeart on top of the next/prev/close buttons. My theme do not apply color box styles.

Swipe is cool :)  may be it should move images a bit faster.

**Comment by juek** [comment]
> Also when using jquerry zoom and simple box1 style - image appeart on top of the next/prev/close buttons. My theme do not apply color box styles.

I wonder where this might come from. Below is the colorbox markup including the img.zoomImg element. All the control buttons are following siblings of div#cboxLoadedContent and get additional 
#cboxPrevious, #cboxNext, #cboxClose { position: absolute; [...] z-index: 10; } 
from /addons/ColorboxExtender/styles/simple_box_1/style.css
That's the only z-index I can see with your settings. Therefore the buttons should always render on top of div#cboxLoadedContent>img.zoomImg. Must be some other css interfering, IMO.

```
<div id="cboxContent">
  <div id="cboxLoadedContent">
    <img class="cboxPhoto" src="/some/image.jpg"/>
    <img class="zoomImg zoomEnabled" src="/same/image.jpg"/>
  </div>
  <div id="cboxTitle">Blah</div>
  <div id="cboxCurrent">Image 1 of 3</div>
  <button id="cboxPrevious">Previous</button>
  <button id="cboxNext">Next</button>
  <button id="cboxSlideshow"></button>
  <div id="cboxLoadingOverlay"></div>
  <div id="cboxLoadingGraphic"></div>
  <button id="cboxClose">Close</button>
</div>
```

**Comment by a2exfr** [comment]
I have no css for color box. 
But all display good when add to 
`<div id="cboxLoadedContent"></div>`

z-index:0  or  z-index:auto   it  comes with no z-index attribute

**Comment by juek** [comment]
Ah, I see. 

Try [this commit](https://github.com/juek/Colorbox-Extender/commit/97d41b49203189d2e5d8b988db85a1a0623eebe6). 

I hope it doesn't break pinch-swipe (thomasfrobieter). If it does, we need to play with the z-indices of the control elements.

**Comment by thomasfrobieter** [comment]
Hi, yes i also noticed some bugs with the pinch swipe solution. Needs defenetly more testing .. 

Sadly my time is currently very, very limited by our running drupal projects. I need some holidays to get the Typesetter tasks done ;)
