### ISSUE TITLE
Warning need

### ISSUE THREAD

**Issue by mahotilo** [juek/Colorbox-Extender#6]
It is need to make warning for users, that TS colorbox style should be Example1 for correct work of plugin.

Combination of "Example 2" in TS settings and "Simple box 1" in plugin settings gives broken layout of popup window.

**Comment by juek** [comment]
You're right. We just need to overrule the the Example 2-4 styles (some borders and caption positioning)

**Comment by mahotilo** [comment]
Yes, it's more complicated than I suggested, but the right way :)

**Comment by juek** [comment]
[fixed](https://github.com/juek/Colorbox-Extender/commit/8fd56fdc0cc45f726ea805628dcce243a6aba81d)
