### ISSUE TITLE
Any image in Colorbox

### ISSUE THREAD

**Issue by mahotilo** [juek/Colorbox-Extender#7]
I have a problem with showing any images in Colorbox. 
Colorbox opened. --> Loading image animation (No image).

I tried it also with my own class (named fotobox) for colorbox href. Plugin option "All pages" in is off.
It works fine without plugin. But with plugin I have same result and for link with my colorbox style.
It appears with any plugin option configurations, on local and online sites.
Image size (in kb) is small enough.

**Comment by juek** [comment]
Hmm. Works here. 
Maybe a collision with some of your own custom JS? Any errors in the browser console?

> Plugin option "All pages" in is off.

This must be enabled in order to work.

**Comment by mahotilo** [comment]
> Maybe a collision with some of your own custom JS? Any errors in the browser console?

No, I have only Colorbox Extender + Simple Blog. Theme is "Bootswatch_Scss" without changes.

Yes, I have an error

```
 Uncaught TypeError: $(...).dotdotdot is not a function
    at HTMLDocument.<anonymous> (Child_Page:132)
    at j (jquery.js:2)
    at Object.fireWith [as resolveWith] (jquery.js:2)
    at Function.ready (jquery.js:2)
    at HTMLDocument.J (jquery.js:2)
```

**Comment by juek** [comment]
dotdotdot (a jQuery text truncation plugin) is new for TS 5.1
Is your installation up to date with the current master or did you only replace some gallery related files. 

Please check if you have /include/thirdparty/dotdotdot/[3 files here]

dotdotdot gets called (only) [from here](https://github.com/Typesetter/Typesetter/blob/9e198fb2d1b333efffdf6979a35647571331dc23/include/tool.php#L891)

**Comment by mahotilo** [comment]
I just create clear TS-master + CBE-master installation on my 127.0.0.1:8080. Standard theme, no plugins 
Same problem. Same error.
```
Uncaught TypeError: $(...).dotdotdot is not a function
    at HTMLDocument.<anonymous> ((index):145)
    at j (jquery.js:3148)
    at Object.fireWith [as resolveWith] (jquery.js:3260)
    at Function.ready (jquery.js:3472)
    at HTMLDocument.J (jquery.js:3503)
```
Gallery work fine, alone image with colorbox style and link on itself show permanent loading animation,
Dotdotdot is on place.
But I have only (Are You counting readme?)
```
22.05.2017  11:08            jquery.dotdotdot.js
22.05.2017  11:08            jquery.dotdotdot.min.js
22.05.2017  11:08            README.md

```

**Comment by mahotilo** [comment]
And server, where I found a problem is online on usual hosting and have last official TS-5.03

**Comment by juek** [comment]
> But I have only (Are You counting readme?)

Yes, that's fine.

I have to check what happens here.

**Comment by juek** [comment]
> ... image with colorbox style and link on itself show permanent loading animation,

Just a suspicion. An image linking to itself might prevent the 'load' event colorbox needs to consider the loading process as completed.

**Comment by mahotilo** [comment]
No, I Make link to different file - same result

**Comment by juek** [comment]
With a plain 5.0.3 installation you shouldn't get the $(...).dotdotdot JS error

**Comment by mahotilo** [comment]
Yes indeed, I have not. But...

![1](https://cloud.githubusercontent.com/assets/14929385/26667658/eb789cd0-46ae-11e7-8554-f0aa92428b9e.png)

**Comment by juek** [comment]
The 'colorbox' class needs to be set on the surrounding anchor, not the image itself.

See the [code example](https://github.com/juek/Colorbox-Extender#usage)

**Comment by mahotilo** [comment]
Oops. Sorry. 
What is surprising, I did everything right with my class for years. And here...
Errāre humānum est.
Once again sorry and many thanks

**Comment by juek** [comment]
;o)

Just added "a." to [the selector](https://github.com/juek/Colorbox-Extender/commit/3e417e30ba4ac868ebd4e21bfb1225ebc030c897)

**Comment by mahotilo** [comment]
Thx, it's a good fool protection and reminder for people like me who like tests CMS in 01:30

**Comment by juek** [comment]
> Uncaught TypeError: $(...).dotdotdot is not a function...

Thanks for spotting this one.
I forgot to push this [commit](https://github.com/Typesetter/Typesetter/commit/420a9647322c4dd5b8df71f4f209985a2ab48a35)
