### ISSUE TITLE
MediaWiki style and Example>1

### ISSUE THREAD

**Issue by mahotilo** [juek/Colorbox-Extender#8]
Jurgen,
the problem with caption positioning and overlapping was not in my theme. 
It is our old "friend" - Colorbox Style "Example3".  MediaWiki style depending on it.
After changing to  "Example1" all glitches go out.
It is need to make in MediaWiki style same changes like in Simple Box to make it independed on Colorbox Style in General Settings/Interface

Fuh, it was long bug hunting:)

**Comment by juek** [comment]
> It is need to make in MediaWiki style same changes like in Simple Box

Should be fixed with [this commit](https://github.com/juek/Colorbox-Extender/commit/a198f845135d33de9a74d4713c6bea0aecddd076)
