### ISSUE TITLE
Permanent  loading animation

### ISSUE THREAD

**Issue by mahotilo** [juek/Colorbox-Extender#9]
I have checked.
Permanent  loading animation appears only on second (and next) colorbox opening with
Hammer.js Pinchzoom & Swipe extension. 
Style does not matter.
Clicking speed does not matter also.

**Comment by mahotilo** [comment]
Sorry for making a new issue. I have skipped a2exfr theme Some bugs
I have tried he's proposal and found this way to fix problem
 
in init.js
change line
    $.colorbox.settings.transition="none";
to
    $.colorbox.settings.transition="";

Animation still working on load, but don't stay eternally.

**Comment by juek** [comment]
Thank you. Just[ changed it](https://github.com/juek/Colorbox-Extender/commit/2b5678825f7ebe0e0e6c6376936966b136fec173) and it seems to work here
